import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import DesktopNav from "@/components/nav/DesktopNav";
import Hero from "@/components/home/Hero";
import Features from "@/components/home/Features";
import Footer from "@/components/home/Footer";
import Specialties from "@/components/home/Specialties";
import MobileNav from "@/components/nav/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Law Firm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navNHero}>
          <div className={styles.desktopNav}>
            <DesktopNav />
          </div>
          <div className={styles.mobileNav}>
            <MobileNav />
          </div>
          <Hero className={styles.hero} />
        </div>
        <Features className={styles.features} />
        <Specialties className={styles.specialties} />
        <Footer />
      </main>
    </>
  );
}
